version: "3.8"

services:
  auth-api:
    build:
      context: ./auth-api
      dockerfile: ./Dockerfile
    volumes:
      - ./auth-api:/app/
      - ./local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - DATABASE_URL=mysql://6x6jv2z5gl0wzrm7x2is:pscale_pw_rfVJo1JB1CNEPiIsQwVyKUYBiUw1NuaefO3a69QpO2R@aws.connect.psdb.cloud/micro-services-esgi?sslaccept=strict
      - insecure=false
      - PORT=4001
      - USER_API_URL=user-api:4000
      - AUTH_API_URL=auth-api:4001
      - JWT_SECRET=super-secret
      - AUTH_CERT=/certs/auth-api.pem
      - AUTH_KEY=/certs/auth-api-key.pem
      - USER_CERT=/certs/user-api.pem
      - USER_KEY=/certs/user-api-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:14268/api/traces
    ports:
      - 4001:400
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  user-api:
    build:
      context: ./user-api
      dockerfile: ./Dockerfile
    volumes:
      - ./user-api:/app/
      - ./local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - DATABASE_URL=mongodb+srv://tlugat:root@cluster0.jyn0psm.mongodb.net/users-db
      - insecure=false
      - PORT=4000
      - AUTH_API_URL=auth-api:4001
      - USER_API_URL=user-api:4000
      - AUTH_CERT=/certs/auth-api.pem
      - AUTH_KEY=/certs/auth-api-key.pem
      - USER_CERT=/certs/user-api.pem
      - USER_KEY=/certs/user-api-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:14268/api/traces
    ports:
      - 4000:4000
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  notes-api:
    build:
      context: ./notes-api
      dockerfile: ./Dockerfile
    volumes:
      - ./notes-api:/app/
      - ./local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - DATABASE_URL=mongodb+srv://tlugat:root@cluster0.jyn0psm.mongodb.net/notes-db
      - insecure=false
      - PORT=4002
      - AUTH_API_URL=auth-api:4001
      - TAG_API_URL=tags-api:4003
      - NOTE_CERT=/certs/notes-api.pem
      - NOTE_KEY=/certs/notes-api-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:14268/api/traces
    ports:
      - 4002:4000
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  tags-api:
    build:
      context: ./tags-api
      dockerfile: .//Dockerfile
    volumes:
      - ./tags-api:/app/
      - ./local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - DATABASE_URL=mongodb+srv://tlugat:root@cluster0.jyn0psm.mongodb.net/tags-db
      - insecure=false
      - PORT=4003
      - AUTH_API_URL=auth-api:4001
      - TAG_CERT=/certs/tags-api.pem
      - TAG_KEY=/certs/tags-api-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:14268/api/traces
    ports:
      - 4003:4000
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  default:
    external: true
    name: grpc-notes-manager-default
