// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "tag/tag.proto" (package "tag", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TagCRUDService } from "./tag";
import type { DeleteResponse } from "./tag";
import type { DeleteRequest } from "./tag";
import type { UpdateResponse } from "./tag";
import type { UpdateRequest } from "./tag";
import type { AddResponse } from "./tag";
import type { AddRequest } from "./tag";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetResponse } from "./tag";
import type { GetRequest } from "./tag";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service tag.TagCRUDService
 */
export interface ITagCRUDServiceClient {
    /**
     * @generated from protobuf rpc: Get(tag.GetRequest) returns (tag.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: Add(tag.AddRequest) returns (tag.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse>;
    /**
     * @generated from protobuf rpc: Update(tag.UpdateRequest) returns (tag.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * @generated from protobuf rpc: Delete(tag.DeleteRequest) returns (tag.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * @generated from protobuf service tag.TagCRUDService
 */
export class TagCRUDServiceClient implements ITagCRUDServiceClient, ServiceInfo {
    typeName = TagCRUDService.typeName;
    methods = TagCRUDService.methods;
    options = TagCRUDService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Get(tag.GetRequest) returns (tag.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Add(tag.AddRequest) returns (tag.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRequest, AddResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(tag.UpdateRequest) returns (tag.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(tag.DeleteRequest) returns (tag.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
